service: cloudwatch-public-metrics

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:GetMetricStatistics"
      Resource: "*"

custom:
  serverless-nextjs:
    nextConfigDir: ./
    pageConfig:
      post:
        events:
          - http:
              path: post/{slug}

package:
  exclude:
    - ./**

plugins:
  - serverless-nextjs-plugin
  - serverless-offline
